### PR TITLE
Readability improvements, added login, fix error

### PR DESCRIPTION
**Pull request by JonasBovin**
Added image names to Jenkins instead of just scan, scan 2, scan 3
fixed index out of bounds when no html in output
changed to use USER 0 instead of root

### CODE REVIEW

**Comment by lizrice** [comment]
LGTM. @oranmoshai would you have time to test?

**Comment by oranmoshai** [comment]
Hi,
After reviewing the changes  there is 2 issues

1. On disallowed there is scanout.null output.
image

2. on allowed the html output not showing HTML
image

**Comment by oranmoshai** [comment]
Hi @JonasBovin can you resolve the issues above?

**Comment by JonasBovin** [comment]
I'll get right on it...

**Comment by oranmoshai** [comment]
@JonasBovin Thank you! merged will be out on next release.

**Pull request merged**
